# Generated by Django 4.2.4 on 2023-08-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solutions", "0003_ferramenta_rename_clientes_cliente_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caixa",
            name="gasto",
        ),
        migrations.RemoveField(
            model_name="caixa",
            name="lucro",
        ),
        migrations.AddField(
            model_name="caixa",
            name="descricao",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name="caixa",
            name="gastos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="caixa",
            name="lucros",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cliente",
            name="endereco",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
